# Global content
title: Andy Bell - Designer & Front-End Developer
asset_version: 0.1.0
asset_base: https://assets.hankchizljaw/assets
posts_per_page: 4
posts_root: /writing/

# Permalink settings
permalink: /writing/:title

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - front-end

# Navigation
navigation:
  - text: Home
    url: /
  - text: Writing
    url: /writing/
  - text: Contact
    url: /contact/

# Footer links
footer_links: 
  - text: Twitter
    url: //twitter.com/hankchizljaw
  - text: GitHub
    url: //github.com/hankchizljaw
  - text: About
    url: /about/
