# Linkage settings
url: &url ""
baseurl: *url
permalink: "/writing/:title/"

# Build settings
markdown: "kramdown"
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "front-end"

# Global content
title: "Andy Bell - Front-End Developer And Designer"
asset_version: "v1.3.0"
asset_base: "https://assets.hankchizljaw.io/assets"
posts_per_page: 4
posts_root: !concat [*url, "/writing/"]
email_address: "andy@hankchizljaw.io"
twitter_handle: &twitter_handle "hankchizljaw"

# Navigation
navigation:
  - text: "Home"
    url: "/" 
  - text: "Work"
    url: "/work/"
  - text: "Writing"
    url: "/writing/"
  - text: "Contact"
    url: "/contact/"

# Footer links
footer_links:
  - text: "Twitter"
    url: !concat ["//twitter.com/", *twitter_handle]
  - text: "GitHub"
    url: "//github.com/hankchizljaw"
  - text: "About"
    url: "/about/"
  - text: "Now"
    url: "/now/"

# Collections 
collections:
  works:
    output: true
    permalink: "/work/:title/"

# Default vals
defaults:
  - scope:
      path: ""
      type: "works"
    values:
      layout: "work-item"

# Additional Gems 
gems:
  - "jekyll-redirect-from"