# Linkage settings
url: &url ""
baseurl: *url
permalink: "/writing/:title/"

# Build settings
markdown: "kramdown"
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "front-end"

# Global content
title: "Andy Bell - Front-End Engineer And Designer"
asset_version: "v1.1.0"
asset_base: "https://assets.hankchizljaw.io/assets"
posts_per_page: 4
posts_root: !concat [*url, "/writing/"]
email_address: "me@andy-bell.co.uk"
twitter_handle: &twitter_handle "hankchizljaw"

# Navigation
navigation:
  - text: "Home"
    url: "/" 
  - text: "Writing"
    url: "/writing/"
  - text: "Contact"
    url: "/contact/"

# Footer links
footer_links:
  - text: "Twitter"
    url: !concat ["//twitter.com/", *twitter_handle]
  - text: "GitHub"
    url: "//github.com/hankchizljaw"
  - text: "About"
    url: "/about/"
  - text: "Now"
    url: "/now/"

# Additional Gems 
gems:
  - "jekyll-redirect-from"
